Implementation of an SVM classifier.
To do:
- split the data in test and train,
- remove key column,
- test different kernels,
- optimize the parameters for each kernel.

In [12]:
# Imports
import numpy as np
import data_preprocessing as dp
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

In [7]:
# Importing the data
data = dp.data_preprocessing('project_train.csv')

# Remove colum 'key'
data = data.drop('key', axis=1)

# Splitting the data into X and y
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

# Splitting the data into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

Gaussian kernel.
$$exp(-\gamma\|x-x'\|^2)$$
Parameters:
- C correpsonds to trading against simplicity and complexity of the decision surface,
- $\gamma$ corresponds to how far goes the influence of a single example.

In [14]:
# Implement SVM with gaussian kernel and optimize the hyperparameters

def svm_gaussian(X_train, y_train, X_test, y_test):
    # Search for the best hyperparameters
    parameters = [{'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.01, 0.1, 1], 'kernel': ['rbf']}]
    classifier = SVC()
    grid_search = GridSearchCV(estimator=classifier, param_grid=parameters, scoring='accuracy', cv=10, n_jobs=-1)
    grid_search = grid_search.fit(X_train, y_train)
    best_parameters = grid_search.best_params_
    
    # Test best parameters
    test_classifier = SVC(C=best_parameters['C'], gamma=best_parameters['gamma'], kernel=best_parameters['kernel'])
    test_classifier.fit(X_train, y_train)
    y_pred = test_classifier.predict(X_test)

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Accuracy score
    accuracy = accuracy_score(y_test, y_pred)

    return cm, accuracy

In [15]:
cm, accuracy = svm_gaussian(X_train, y_train, X_test, y_test)
print(cm)
print(accuracy)

[[49  4]
 [13 35]]
0.8316831683168316


Polynomial kernel. 
$$(\langle x, x'\rangle + r)^d$$
Parameters:
- degree d of the polynomial (degree),
- offset r (coef0).

In [18]:
def polynomial_svm(X_train, y_train, X_test, y_test):
    # Search for the best hyperparameters
    parameters = [{'C': [1, 10, 100, 1000], 'degree': [2, 3, 4], 'kernel': ['poly']}]
    classifier = SVC()
    grid_search = GridSearchCV(estimator=classifier, param_grid=parameters, scoring='accuracy', cv=10, n_jobs=-1)
    grid_search = grid_search.fit(X_train, y_train)
    best_parameters = grid_search.best_params_
    print(best_parameters)
    
    # Test best parameters
    test_classifier = SVC(C=best_parameters['C'], degree=best_parameters['degree'], kernel=best_parameters['kernel'])
    test_classifier.fit(X_train, y_train)
    y_pred = test_classifier.predict(X_test)

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Accuracy score
    accuracy = accuracy_score(y_test, y_pred)

    return cm, accuracy

In [19]:
cm, accuracy = polynomial_svm(X_train, y_train, X_test, y_test)
print(cm)
print(accuracy)

{'C': 100, 'degree': 2, 'kernel': 'poly'}
[[49  4]
 [13 35]]
0.8316831683168316


Sigmoid tanh kernel.
$$tanh(\gamma \langle x, x'\rangle + r)$$

In [22]:
def sigmoid_svm(X_train, y_train, X_test, y_test):
    # Search for the best hyperparameters
    parameters = [{'C': [1, 10, 100, 1000, 10000], 'gamma': [0.0001, 0.001, 0.01, 0.1, 1], 'kernel': ['sigmoid']}]
    classifier = SVC()
    grid_search = GridSearchCV(estimator=classifier, param_grid=parameters, scoring='accuracy', cv=10, n_jobs=-1)
    grid_search = grid_search.fit(X_train, y_train)
    best_parameters = grid_search.best_params_
    print(best_parameters)
    
    # Test best parameters
    test_classifier = SVC(C=best_parameters['C'], gamma=best_parameters['gamma'], kernel=best_parameters['kernel'])
    test_classifier.fit(X_train, y_train)
    y_pred = test_classifier.predict(X_test)

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Accuracy score
    accuracy = accuracy_score(y_test, y_pred)

    return cm, accuracy

In [24]:
cm, accuracy = sigmoid_svm(X_train, y_train, X_test, y_test)
print(cm)
print(accuracy)

{'C': 1000, 'gamma': 0.001, 'kernel': 'sigmoid'}
[[48  5]
 [14 34]]
0.8118811881188119
